exports.OWN_PLAYER_SNAKE_BODY = '#00FF26';
exports.OWN_PLAYER_SNAKE_OUTLINE = '#1DB835';

exports.OTHER_PLAYER_SNAKE_BODY = '#9FB5CC';
exports.OTHER_PLAYER_SNAKE_OUTLINE = '#5D91C9'

exports.APPLE_BODY = '#FA0F0F';
exports.APPLE_OUTLINE = '#C41010';
exports.APPLE_STEM = '#91531D';
